### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nanoxd**
Updates dependencies to use RxSwift 4.0 and Apollo 0.7

### CODE REVIEW

**Comment by nanoxd** [comment]
Failure is due to unable to download the frameworks.

**Comment by scottrhoyt** [comment]
Thanks for this and sorry for the delay! Let me take a look at the CI failure and hopefully merge soon.

**Comment by nanoxd** [comment]
No worries, thanks!

**Comment by scottrhoyt** [comment]
So, it turns out that the root cause of the CI error was the incompatibility between RxApollo (Swift 3.1), RxSwift 4.0 (Swift 4.0), and the Xcode version on the CI image (Xcode 8.3). I resolved this in separate PRs to update to Swift 4--and RxSwift 4--and updating to Apollo 0.7. I'll cut a release shortly. Thanks again for contributing!

**Comment by nanoxd** [comment]
Thanks for putting the time in to resolve this.

**Pull request closed without merging**
